export const url = 'https://www.apprinting.com/admin/'

export const urlProductUpdatePrice =
  'https://www.apprinting.com/bilingual-wedding-invitations/products/#category_product_list'

export const qtys = [250, 500, 1000, 2500, 5000, 10000, 15000, 20000, 25000]

// https://spys.one/
// const list = document.querySelectorAll(".spy14")
// list.forEach(el => {if(el.innerText.includes(":")){console.log(el.innerText)}})
// list.forEach(el => {if(el.innerText.includes(":")){console.log(`'${el.innerText}',`)}})

// https://freeproxylist.cc/
// const list = document.querySelectorAll('[role="row"]')
// list.forEach(el => {if(el.innerText.includes(".")){console.log(el.innerText)}if(el.innerText.search("/[^0-9]/g")){console.log(el.innerText)}})

export const proxies = [
  '40.76.69.94:8080',
  '167.99.124.118:80',
  '47.251.87.74:9080',
  '108.161.128.43:80',
  '144.126.216.57:80',
  '68.183.143.134:80',
  '148.72.140.24:30127',
  '47.88.31.196:8080',
  '47.252.29.28:11222',
  '47.251.43.115:33333',
  '47.251.73.54:9098',
  '138.197.102.119:80',
  '138.91.159.185:80',
  '47.90.205.231:33333',
  '173.255.119.18:80',
  '162.223.90.13:80',
  '47.252.18.37:80',
  '198.49.68.80:80',
  '154.16.146.46:80',
  '154.85.58.149:80',
  '138.68.235.51:80',
  '192.73.244.36:80',
  '154.16.146.44:80',
  '154.16.146.48:80',
  '159.65.245.255:80',
  '162.214.165.203:80',
  '172.173.132.85:80',
  '161.35.49.68:80',
  '148.72.165.7:30118',
  '47.252.18.37:8443',
  '137.184.100.135:80',
  '154.16.146.42:80',
  '47.90.167.27:9080',
  '144.86.187.37:3129',
  '198.74.51.79:8888'

]

export const idProducts = [
  5452,
  5196,
  5584,
  5667,
  4612,
  5674,
  5678,
  5684,
  5687,
  5689,
  5691,
  5696,
  5698,
  5701,
  5703,
  5705,
  5707,
  5709,
  5713,
  5731,
  4673

]

export const titlesProducts = [
  'AP-[I-14] Subtle Sophistication Flowers Wedding Invitation',
  'K778 [I-12] Whispers of Elegance Flowers Wedding Invitation',
  'ART-08250 [I-10] Delicate Elegance Flowers Wedding Invitation',
  'ART-44995 [I-11] Blossom Bells & Flowers Wedding Invitation',
  'ART-41009 [I-11] Charming Bellflowers Wedding Invitation',
  'ART-80494 [I-09] Flowers Wedding Invitation',
  'ART-84044 [I-11] Flowers Wedding Invitation',
  'K1618 [I-11] Timeless Elegance Flowers Wedding Invitation',
  'K2615 [I-10] Flowers Sophistication Wedding Invitation',
  'K8358 [I-12] Lavender Love Flowers Wedding Invitation',
  'K8455 [I-11] Serenade of Flowers Wedding Invitation',
  'Olive Garden Flowers Wedding Invitation',
  'Olive Garden RSVP Cards Flowers Wedding Invitation',
  'Olive Garden Enclosure Cards Flowers Wedding Invitation',
  'K8536 [I-11] Graceful Garden Flowers Wedding Invitation',
  'Olive Garden Seals Flowers Wedding Invitation',
  'K8631 [I-11] Blushing Blooms Flowers Wedding Invitation',
  'K8781 [I-11] Celebration in Flowers Wedding Invitation',
  'K8784 [I-11] Spring Harmony Flowers Wedding Invitation',
  'K9152 [I-11] Harmony in Bloom Flowers Wedding Invitation',
  'K9649 [I-11] Enchanted Petals & Flowers Wedding Invitation',
  'K9659 [I-11] Soulful Blooms Flowers Wedding Invitation',
  'K9995 [I-10] Botanical Elegance Flowers Wedding Invitation',
  'T1402 [I-15] Silk Flowers Beauty Wedding Invitation',
  'K8071 [I-10] Flowers Symphony Wedding Invitation',
  'Deco Art [CC-55] Romantic Petal Cascade Flowers Wedding Invitation',
  'Delicate Blossoms [CC-35] Fresh Flowers Wedding Invitation',
  '[CC-20] Figured Letters Flowers Wedding Invitation',
  '[CC-25] Naturally Sweet Flowers Wedding Invitation',
  '[CC-05] Pearlized Filigree Border Floral Wedding Invitation',
  '[CC-25] Swirling Romance Flowers Wedding Invitation',
  '[CC-20] Swirled in Silver Flowers Wedding Invitation',
  '[CC-15] Bright White Calla Lily Floral Wedding Invitation',
  '[CC-26] Exquisite Poetry Flowers Wedding Invitation',
  '[CC-20] Filigree Splash Flowers Wedding Invitation',
  '[CC-26] Lace Shimmers Flowers Wedding Invitation',
  '[CC-26] Swirl of Gold Flowers Wedding Invitation'
]

export const urlsProducts = [
  'https://www.apprinting.com/blue-flowers-and-leaves-wedding-invitation/',
  'https://www.apprinting.com/tropical-leaves-wedding-invitation/',
  'https://www.apprinting.com/pink-flowers-wedding-invitation/',
  'https://www.apprinting.com/watercolor-blue-roses-wedding-invitation/',
  'https://www.apprinting.com/inspirational-pink-flowers-wedding-invitation/',
  'https://www.apprinting.com/blue-flowers-wedding-invitation/',
  'https://www.apprinting.com/coffee-stained-flowers-wedding-invitation/',
  'https://www.apprinting.com/burgundy-leaves-wedding-invitation/',
  'https://www.apprinting.com/multicolored-rose-bouquet-wedding-invitation/',
  'https://www.apprinting.com/blue-and-gold-leaves-wedding-invitation/',
  'https://www.apprinting.com/warm-fall-flowers-wedding-invitation/',
  'https://www.apprinting.com/botanical-yellow-flowers-wedding-invitation/',
  'https://www.apprinting.com/abstract-golden-waves-wedding-invitation/',
  'https://www.apprinting.com/pastel-green-flowers-wedding-invitation/',
  'https://www.apprinting.com/deep-blue-watercolor-wedding-invitation/',
  'https://www.apprinting.com/bright-spring-floral-wedding-invitation/',
  'https://www.apprinting.com/gentle-pink-bouquet-wedding-invitation/',
  'https://www.apprinting.com/floral-soft-pink-wedding-invitation/',
  'https://www.apprinting.com/dusty-roses-delicate-wedding-invitation/',
  'https://www.apprinting.com/pastel-watercolor-wedding-invitation/',
  'https://www.apprinting.com/pink-spring-flowers-wedding-invitation/',
  'https://www.apprinting.com/peach-flowers-wedding-invitation/',
  'https://www.apprinting.com/rustic-floral-wedding-invitation/',
  'https://www.apprinting.com/simple-large-cursive-wedding-invitation/',
  'https://www.apprinting.com/elegant-green-leaves-wedding-invitation/',
  'https://www.apprinting.com/elegant-brown-leaves-wedding-invitation/',
  'https://www.apprinting.com/pink-paint-strokes-wedding-invitation/',
  'https://www.apprinting.com/ashen-gray-flowers-wedding-invitation/',
  'https://www.apprinting.com/handmade-flower-set-wedding-invitation/',
  'https://www.apprinting.com/handmade-flower-silhouettes-wedding-invitation/',
  'https://www.apprinting.com/soft-leaf-border-wedding-invitation/',
  'https://www.apprinting.com/teal-watercolor-wedding-invitation/',
  'https://www.apprinting.com/elegant-leaves-wedding-invitation/',
  'https://www.apprinting.com/showy-spring-flowers-wedding-invitation/',
  'https://www.apprinting.com/green-and-gray-leaves-wedding-invitation/',
  'https://www.apprinting.com/explosive-watercolor-wedding-invitation/',
  'https://www.apprinting.com/fuchsia-lines-wedding-invitation/',
  'https://www.apprinting.com/green-and-roses-wedding-invitation/',
  'https://www.apprinting.com/luxury-indian-frames-wedding-invitation/',
  'https://www.apprinting.com/gold-plated-leaves-wedding-invitation/',
  'https://www.apprinting.com/bright-flowers-wedding-invitation/',
  'https://www.apprinting.com/sparkling-blue-watercolor-wedding-invitation/',
  'https://www.apprinting.com/luxurious-gold-wedding-invitation/',
  'https://www.apprinting.com/gold-frames-wedding-invitation/',
  'https://www.apprinting.com/cloudy-blue-wedding-invitation/',
  'https://www.apprinting.com/golden-flowers-wedding-invitation/',
  'https://www.apprinting.com/simplicity-and-elegance-wedding-invitation/',
  'https://www.apprinting.com/golden-frame-and-leaves-wedding-invitation/',
  'https://www.apprinting.com/aztec-design-wedding-invitation/',
  'https://www.apprinting.com/elegant-frames-wedding-invitation/',
  'https://www.apprinting.com/golden-corner-flowers-wedding-invitation/',
  'https://www.apprinting.com/rustic-green-leaves-wedding-invitation/',
  'https://www.apprinting.com/golden-leaves-wedding-invitation/',
  'https://www.apprinting.com/vintage-golden-flowers-wedding-invitation/',
  'https://www.apprinting.com/classic-wedding-invitation/',
  'https://www.apprinting.com/blue-and-gold-watercolor-wedding-invitation/',
  'https://www.apprinting.com/simple-flowers-gray-wedding-invitation/',
  'https://www.apprinting.com/blue-golden-flowers-wedding-invitation/',
  'https://www.apprinting.com/minimalist-class-wedding-invitation/',
  'https://www.apprinting.com/vintage-geometric-flowers-wedding-invitation/',
  'https://www.apprinting.com/elegant-golden-frame-wedding-invitation/',
  'https://www.apprinting.com/golden-mandala-wedding-invitation/',
  'https://www.apprinting.com/green-tropical-leaves-wedding-invitation/',
  'https://www.apprinting.com/dark-teal-frame-wedding-invitation/',
  'https://www.apprinting.com/elegant-blue-flowers-wedding-invitation/',
  'https://www.apprinting.com/gold-streaked-sandy-wedding-invitation/',
  'https://www.apprinting.com/copper-stroke-wedding-invitation/',
  'https://www.apprinting.com/gold-trim-wedding-invitation/',
  'https://www.apprinting.com/diffused-blue-droplets-wedding-invitation/',
  'https://www.apprinting.com/blue-purple-brushes-wedding-invitation/',
  'https://www.apprinting.com/glittering-desert-wedding-invitation/',
  'https://www.apprinting.com/pink-and-fuchsia-wedding-invitation/',
  'https://www.apprinting.com/golden-elegance-wedding-invitation/',
  'https://www.apprinting.com/noisy-grays-wedding-invitation/',
  'https://www.apprinting.com/faint-green-ombre-wedding-invitation/',
  'https://www.apprinting.com/pink-and-gray-marble-wedding-invitation/',
  'https://www.apprinting.com/deep-fose-tint-wedding-invitation/',
  'https://www.apprinting.com/splash-of-blush-wedding-invitation/',
  'https://www.apprinting.com/abstract-blue-paint-wedding-invitation/',
  'https://www.apprinting.com/simple-red-flowers-wedding-invitation/',
  'https://www.apprinting.com/refined-black-floral-wedding-invitation/',
  'https://www.apprinting.com/watercolor-sea-water-wedding-invitation/',
  'https://www.apprinting.com/watercolor-earth-tones-wedding-invitation/',
  'https://www.apprinting.com/green-watercolor-wedding-invitation/',
  'https://www.apprinting.com/simple-pink-wedding-invitation/',
  'https://www.apprinting.com/golden-leaves-wedding-invitation-2040/',
  'https://www.apprinting.com/classic-gold-edge-wedding-invitation/',
  'https://www.apprinting.com/white-cherry-blossoms-wedding-invitation/',
  'https://www.apprinting.com/pink-and-red-flowers-wedding-invitation/',
  'https://www.apprinting.com/golden-chinese-lamps-wedding-invitation/',
  'https://www.apprinting.com/blue-frame-clouds-wedding-invitation/',
  'https://www.apprinting.com/golden-invitation-clouds-wedding-invitation/',
  'https://www.apprinting.com/bluish-green-bamboo-wedding-invitation/',
  'https://www.apprinting.com/golden-bamboo-stalks-wedding-invitation/',
  'https://www.apprinting.com/festive-chinese-wedding-invitation/',
  'https://www.apprinting.com/blooming-pink-flowers-wedding-invitation/',
  'https://www.apprinting.com/radiating-gold-flowers-wedding-invitation/',
  'https://www.apprinting.com/golden-lanterns-and-branches-wedding-invitation/',
  'https://www.apprinting.com/pink-and-red-falling-wedding-invitation/',
  'https://www.apprinting.com/lanterns-bright-flowers-wedding-invitation/',
  'https://www.apprinting.com/artistic-cloud-borders-wedding-invitation-2639/',
  'https://www.apprinting.com/burgundy-flowers-wedding-invitation/',
  'https://www.apprinting.com/lanterns-and-celebration-flowers-wedding-invitation/',
  'https://www.apprinting.com/soft-golden-bamboo-wedding-invitation/',
  'https://www.apprinting.com/chinese-lamp-wedding-invitation/',
  'https://www.apprinting.com/dark-blue-wedding-invitation/',
  'https://www.apprinting.com/golden-borders-and-tigers-wedding-invitation/',
  'https://www.apprinting.com/faint-palace-and-lanterns-wedding-invitation/',
  'https://www.apprinting.com/ombre-lanterns-wedding-invitation/',
  'https://www.apprinting.com/flowers-and-lanterns-swaying-wedding-invitation/',
  'https://www.apprinting.com/song-hy-and-gold-borders-wedding-invitation/',
  'https://www.apprinting.com/delicate-bamboo-art-wedding-invitation/',
  'https://www.apprinting.com/hanging-lanterns-and-charms-wedding-invitation/',
  'https://www.apprinting.com/fan-and-artistic-flowers-wedding-invitation/',
  'https://www.apprinting.com/red-border-and-clouds-wedding-invitation/',
  'https://www.apprinting.com/printed-corners-and-flowers-wedding-invitation/',
  'https://www.apprinting.com/festive-lanterns-in-a-sky-wedding-invitation/',
  'https://www.apprinting.com/bright-red-and-cloud-scroll-wedding-invitation/',
  'https://www.apprinting.com/white-clouds-on-dark-red-wedding-invitation/',
  'https://www.apprinting.com/chinese-mountain-and-river-wedding-invitation/',
  'https://www.apprinting.com/bright-flower-border-wedding-invitation/',
  'https://www.apprinting.com/round-hanging-lanterns-wedding-invitation/',
  'https://www.apprinting.com/artistic-cloud-borders-wedding-invitation/',
  'https://www.apprinting.com/refined-edge-pattern-wedding-invitation/',
  'https://www.apprinting.com/elegant-bouquet-of-flowers-wedding-invitation/',
  'https://www.apprinting.com/simple-flat-wedding-invitation-template-miguel/',
  'https://www.apprinting.com/gradient-gold-and-red-wedding-invitation/',
  'https://www.apprinting.com/modern-dragon-valances-wedding-invitation/',
  'https://www.apprinting.com/oriental-patterned-borders-wedding-invitation/',
  'https://www.apprinting.com/minimalist-white-wedding-invitation/',
  'https://www.apprinting.com/beautiful-red-white-gold-wedding-invitation/',
  'https://www.apprinting.com/golden-geometric-corners-wedding-invitation/',
  'https://www.apprinting.com/chinese-lanterns-wedding-invitation/',
  'https://www.apprinting.com/bouquets-of-pink-flowers-wedding-invitation/',
  'https://www.apprinting.com/simple-oriental-wedding-invitation/',
  'https://www.apprinting.com/clouds-and-flowers-environment-wedding-invitation/',
  'https://www.apprinting.com/blue-snow-wedding-invitation/',
  'https://www.apprinting.com/pink-christmas-wedding-invitation/',
  'https://www.apprinting.com/christmas-pineapple-design-wedding-invitation/',
  'https://www.apprinting.com/floral-winter-wedding-invitation/',
  'https://www.apprinting.com/delicate-snow-debris-wedding-invitation/',
  'https://www.apprinting.com/christmas-pine-branches-wedding-invitation/',
  'https://www.apprinting.com/winter-forest-wedding-invitation/',
  'https://www.apprinting.com/christmas-brown-branches-wedding-invitation/',
  'https://www.apprinting.com/cold-and-tender-flowers-wedding-invitation/',
  'https://www.apprinting.com/frame-snowflakes-wedding-invitation/',
  'https://www.apprinting.com/blue-roses-leaves-wedding-invitation/',
  'https://www.apprinting.com/arrangement-of-winter-roses-wedding-invitation/',
  'https://www.apprinting.com/classic-christmas-design-simple-flat-wedding-invitation/',
  'https://www.apprinting.com/christmas-corners-wedding-invitation/',
  'https://www.apprinting.com/realistic-pine-tree-wedding-invitation/',
  'https://www.apprinting.com/blue-christmas-simple-flat-5x7/',
  'https://www.apprinting.com/christmas-decoration-simple-flat-5x7/',
  'https://www.apprinting.com/cold-watercolor-frame-wedding-invitation/',
  'https://www.apprinting.com/roses-mary-wedding-invitation/',
  'https://www.apprinting.com/minimalist-winter-leaves-wedding-invitation/',
  'https://www.apprinting.com/christmas-leaves-wedding-invitation/',
  'https://www.apprinting.com/royal-pine-frame-wedding-invitation/',
  'https://www.apprinting.com/winter-cream-roses-wedding-invitation/',
  'https://www.apprinting.com/elegant-watercolor-leaves-wedding-invitation/',
  'https://www.apprinting.com/winter-festival-wedding-invitation/',
  'https://www.apprinting.com/loving-snowflakes-wedding-invitation/',
  'https://www.apprinting.com/purple-winter-floral-wedding-invitation/',
  'https://www.apprinting.com/winter-roses-and-leaves-wedding-invitation/',
  'https://www.apprinting.com/modest-roses-wedding-invitation/',
  'https://www.apprinting.com/purple-flower-arrangement-wedding-invitation/',
  'https://www.apprinting.com/golden-leaves-wedding-invitation-2747/',
  'https://www.apprinting.com/white-winter-roses-wedding-invitation/',
  'https://www.apprinting.com/winter-leaves-and-gradient-wedding-invitation/',
  'https://www.apprinting.com/hexagonal-roses-arrangement-wedding-invitation/',
  'https://www.apprinting.com/winter-pines-landscape-wedding-invitation/',
  'https://www.apprinting.com/flowers-and-cold-leaves-wedding-invitation/',
  'https://www.apprinting.com/dark-winter-design-wedding-invitation/',
  'https://www.apprinting.com/winter-geometric-arrangement-wedding-invitation/',
  'https://www.apprinting.com/christmas-and-gold-frame-wedding-invitation/',
  'https://www.apprinting.com/modest-white-flowers-wedding-invitation/',
  'https://www.apprinting.com/pine-and-wood-design-wedding-invitation/',
  'https://www.apprinting.com/winter-design-photo-wedding-invitation/',
  'https://www.apprinting.com/black-snowflakes-wedding-invitation/',
  'https://www.apprinting.com/pine-cone-and-roses-wedding-invitation/',
  'https://www.apprinting.com/watercolor-pines-wedding-invitation/',
  'https://www.apprinting.com/dark-invitation-snowflakes-wedding-invitation/',
  'https://www.apprinting.com/geometric-frame-branches-wedding-invitation/',
  'https://www.apprinting.com/dark-invitation-flowers-wedding-invitation/',
  'https://www.apprinting.com/wooden-frame-snowflakes-wedding-invitation/',
  'https://www.apprinting.com/blue-floral-silhouettes-wedding-invitation/',
  'https://www.apprinting.com/brown-and-white-flower-wedding-invitation/',
  'https://www.apprinting.com/simple-pine-branches-wedding-invitation/',
  'https://www.apprinting.com/wood-white-forest-wedding-invitation/',
  'https://www.apprinting.com/purple-flowers-wedding-invitation/',
  'https://www.apprinting.com/subtle-blue-flowers-wedding-invitation/',
  'https://www.apprinting.com/cardboard-design-flowers-wedding-invitation/',
  'https://www.apprinting.com/winter-flowers-and-frame-wedding-invitation/',
  'https://www.apprinting.com/wood-winter-ligths-wedding-invitation/',
  'https://www.apprinting.com/leaves-and-branches-gradient-wedding-invitation/',
  'https://www.apprinting.com/cardboard-white-branches-wedding-invitation/',
  'https://www.apprinting.com/indian-wedding-ganesha-wedding-invitation/',
  'https://www.apprinting.com/boho-arrows-wedding-invitation/',
  'https://www.apprinting.com/golden-waves-wedding-invitation/',
  'https://www.apprinting.com/eucalyptus-flower-wedding-invitation/',
  'https://www.apprinting.com/laser-cut-blue-wedding-invitation/',
  'https://www.apprinting.com/tropical-stationery-in-peach-wedding-invitation/',
  'https://www.apprinting.com/red-invitation-leaves-wedding-invitation/',
  'https://www.apprinting.com/elegant-beige-and-black-wedding-invitation/',
  'https://www.apprinting.com/elegant-golden-mandala-wedding-invitation/',
  'https://www.apprinting.com/elegant-gold-decorations-wedding-invitation/',
  'https://www.apprinting.com/flowers-and-turquoise-watercolor-wedding-invitation/',
  'https://www.apprinting.com/design-boho-photo-wedding-invitation/',
  'https://www.apprinting.com/cream-colored-boho-wedding-invitation/',
  'https://www.apprinting.com/couple-decorative-borders-wedding-invitation/',
  'https://www.apprinting.com/minimalist-pink-border-wedding-invitation/',
  'https://www.apprinting.com/ornamental-invitation-photo-wedding-invitation/',
  'https://www.apprinting.com/beige-abstract-shapes-wedding-invitation/',
  'https://www.apprinting.com/simple-photo-invitation-wedding-invitation/',
  'https://www.apprinting.com/luxury-gradient-photo-wedding-invitation/',
  'https://www.apprinting.com/gatsby-style-in-gold-wedding-invitation/',
  'https://www.apprinting.com/elegant-white-and-flowers-wedding-invitation/',
  'https://www.apprinting.com/elegant-simple-wedding-invitation/'
]
