const products = [
  { id: 5450, title: "4th of July Posters" },
  { id: 24, title: "Posters" },
  { id: 3781, title: "Posters Labor Day White" },
  { id: 3784, title: "Posters Labor Day with Lawns" },
  { id: 3785, title: "Hand Drawn Labor Day" },
  { id: 3786, title: "Posters Flat Labor Day" },
  { id: 3787, title: "Posters Realistic Labor Day" },
  { id: 3789, title: "Posters Labor Day with Confetti" },
  { id: 3791, title: "Posters Labor Day with Construction" },
  { id: 3793, title: "Posters Labor Day Sale" },
  { id: 3794, title: "Posters Gradient Labor Day" },
  { id: 3820, title: "Beautiful Apartment Posters" },
  { id: 3822, title: "Beautiful Chalet Posters" },
  { id: 3824, title: "Nice Apartment Complex Posters" },
  { id: 3829, title: "Nice Yellow House Posters" },
  { id: 3830, title: "Elegant Apartment Posters" },
  { id: 3832, title: "Elegant House With Garden Posters" },
  { id: 3835, title: "Beautiful House With Pool Posters" },
  { id: 3844, title: "Large Comfortable House Posters" },
  { id: 3846, title: "Large Black Luxury House Posters" },
  { id: 3848, title: "Nice Old House Posters" },
  { id: 3851, title: "Nice And Warm House Posters" },
  { id: 3853, title: "Incredible Luxury Apartment Posters" },
];

export default products;
