const seoData = [
  [
    `Perfect Bilingual Wedding Invitations for a Multicultural Celebration | AP PRINTING`,
    `Discover elegant bilingual wedding invitations in Vietnamese and English. Create the perfect blend of cultures for your special day. Order now and make your celebration unforgettable.`,
    `{"@context":"https://schema.org/","@type":"Product","name":"K7017 [I-10] Bilingual Wedding Invitation","description":"K7017 [I-10] Bilingual Wedding Invitation. A high-quality product offered by AP PRINTING. Our design team ensures that every detail is perfect to meet our customers' needs.","sku":"K7017_I10","brand":{"@type":"Card","name":"Bilingual Wedding Invitation"},"review":{"@type":"Review","reviewRating":{"@type":"Rating","ratingValue":"4","bestRating":"5"},"author":{"@type":"Person","name":"AP PRINTING DESIGN TEAM"}},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.5","reviewCount":"9825"},"offers": {"@type": "Offer","url": "https://www.apprinting.com/blue-flowers-and-leaves-wedding-invitation/","priceCurrency": "USD","price": "85.00","priceValidUntil": "2024-12-24","itemCondition": "https://schema.org/UsedCondition","availability": "https://schema.org/InStock"}}`,
    `<meta name="keywords" content ="Bilingual Wedding Invitation, Vietnamese Wedding Invitation, English Wedding Invitation, Dual Language Invitations, Cultural Wedding Invitations" />`,
  ],
  [
    `Red and Gold Leaf Bilingual Wedding Invitations to Wow Your Guests | AP PRINTING`,
    `Elevate your wedding with stunning red and gold leaf bilingual invitations. Customizable and elegant, they are perfect for any cultural celebration. Order your unique invitations today!`,
    `{"@context":"https://schema.org/","@type":"Product","name":"K7105-Overlay [I-13] Vietnamese & English Wedding Invitation","description":"K7105-Overlay [I-13] Vietnamese & English Wedding Invitation. A high-quality product offered by AP PRINTING. Our design team ensures that every detail is perfect to meet our customers' needs.","sku":"K7105-Overlay_I13","brand":{"@type":"Card","name":"Bilingual Wedding Invitation"},"review":{"@type":"Review","reviewRating":{"@type":"Rating","ratingValue":"4","bestRating":"5"},"author":{"@type":"Person","name":"AP PRINTING DESIGN TEAM"}},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.5","reviewCount":"6936"},"offers": {"@type": "Offer","url": "https://www.apprinting.com/blue-flowers-and-leaves-wedding-invitation/","priceCurrency": "USD","price": "85.00","priceValidUntil": "2024-12-24","itemCondition": "https://schema.org/UsedCondition","availability": "https://schema.org/InStock"}}`,
    `<meta name="keywords" content ="Red Bilingual Wedding Invitation, Gold Leaf Invitations, Natural Wedding Invitations, Custom Wedding Invitations, Elegant Wedding Stationery" />`,
  ],
  [
    `Luxurious Bilingual Wedding Invitations in Jupiter, Onyx, and Ice Silver | AP PRINTING`,
    `Make your wedding stand out with our luxurious bilingual wedding invitations. Available in Jupiter, Onyx, and Ice Silver, these invites are perfect for an elegant affair. Get yours now!`,
    `{"@context":"https://schema.org/","@type":"Product","name":"T511LT [I-17] Vietnamese & English Wedding Invitation","description":"T511LT [I-17] Vietnamese & English Wedding Invitation. A high-quality product offered by AP PRINTING. Our design team ensures that every detail is perfect to meet our customers' needs.","sku":"T511LT_I17","brand":{"@type":"Card","name":"Bilingual Wedding Invitation"},"review":{"@type":"Review","reviewRating":{"@type":"Rating","ratingValue":"4","bestRating":"5"},"author":{"@type":"Person","name":"AP PRINTING DESIGN TEAM"}},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.7","reviewCount":"8091"},"offers": {"@type": "Offer","url": "https://www.apprinting.com/blue-flowers-and-leaves-wedding-invitation/","priceCurrency": "USD","price": "85.00","priceValidUntil": "2024-12-24","itemCondition": "https://schema.org/UsedCondition","availability": "https://schema.org/InStock"}}`,
    `<meta name="keywords" content ="Jupiter Bilingual Wedding Invitation, Onyx Wedding Invitations, Ice Silver Invitations, Modern Wedding Invitations, Luxurious Wedding Stationery" />`,
  ],
  [
    `Stylish Bilingual Wedding Invitations in Overlay Coral, Gold, and White Gold | AP PRINTING`,
    `Add a touch of style to your wedding with our overlay coral, gold, and white gold bilingual invitations. Perfect for a chic celebration. Shop now and impress your guests!`,
    `{"@context":"https://schema.org/","@type":"Product","name":"O2P-57-N-N-Band Red, Natural, Gold Leaf Bilingual Wedding Invitation","description":"O2P-57-N-N-Band Red, Natural, Gold Leaf Bilingual Wedding Invitation. A high-quality product offered by AP PRINTING. Our design team ensures that every detail is perfect to meet our customers' needs.","sku":"O2P_57_N-N_[O2P-N-N]-Red_Natural_Gold-Leaf_Band","brand":{"@type":"Card","name":"Bilingual Wedding Invitation"},"review":{"@type":"Review","reviewRating":{"@type":"Rating","ratingValue":"4","bestRating":"5"},"author":{"@type":"Person","name":"AP PRINTING DESIGN TEAM"}},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.6","reviewCount":"6420"},"offers": {"@type": "Offer","url": "https://www.apprinting.com/blue-flowers-and-leaves-wedding-invitation/","priceCurrency": "USD","price": "85.00","priceValidUntil": "2024-12-24","itemCondition": "https://schema.org/UsedCondition","availability": "https://schema.org/InStock"}}`,
    `<meta name="keywords" content ="Overlay Coral Bilingual Wedding Invitation, Gold Invitations, White Gold Invitations, Coral Wedding Invitations, Stylish Wedding Stationery" />`,
  ],
  [
    `Romantic Burgundy and White Peony Bilingual Wedding Invitations | AP PRINTING`,
    `Capture the essence of romance with our burgundy and white peony bilingual wedding invitations. Available in Spanish and English, these invites are perfect for a beautiful wedding. Order today!`,
    `{"@context":"https://schema.org/","@type":"Product","name":"PAL-66-MMM Jupiter, Onyx, Ice Silver Bilingual Wedding Invitation","description":"PAL-66-MMM Jupiter, Onyx, Ice Silver Bilingual Wedding Invitation. A high-quality product offered by AP PRINTING. Our design team ensures that every detail is perfect to meet our customers' needs.","sku":"PAL_66_MMM_[ac8008]-Jupiter_Onyx_Ice-Silver","brand":{"@type":"Card","name":"Bilingual Wedding Invitation"},"review":{"@type":"Review","reviewRating":{"@type":"Rating","ratingValue":"4","bestRating":"5"},"author":{"@type":"Person","name":"AP PRINTING DESIGN TEAM"}},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.3","reviewCount":"6416"},"offers": {"@type": "Offer","url": "https://www.apprinting.com/blue-flowers-and-leaves-wedding-invitation/","priceCurrency": "USD","price": "85.00","priceValidUntil": "2024-12-24","itemCondition": "https://schema.org/UsedCondition","availability": "https://schema.org/InStock"}}`,
    `<meta name="keywords" content ="Burgundy and White Peony Wedding Invitation, Spanish Wedding Invitation, English Wedding Invitation, Floral Wedding Invitations, Romantic Wedding Stationery" />`,
  ],
  [
    `Celebrate Love with Spanish & English Bilingual Wedding Invitations | AP PRINTING`,
    `Create lasting memories with our Spanish and English bilingual wedding invitations. Perfect for Hispanic weddings, these invites are beautifully designed. Order now to celebrate your love!`,
    `{"@context":"https://schema.org/","@type":"Product","name":"PSQ-77-NMM-2WL Overlay Coral, Gold, White Gold Bilingual Wedding Invitation","description":"PSQ-77-NMM-2WL Overlay Coral, Gold, White Gold Bilingual Wedding Invitation. A high-quality product offered by AP PRINTING. Our design team ensures that every detail is perfect to meet our customers' needs.","sku":"PSQ_77_NMM_2WL_[ac8023M-2Bse-2Top-7x7]-Coral_Gold_White-Gold","brand":{"@type":"Card","name":"Bilingual Wedding Invitation"},"review":{"@type":"Review","reviewRating":{"@type":"Rating","ratingValue":"4","bestRating":"5"},"author":{"@type":"Person","name":"AP PRINTING DESIGN TEAM"}},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.2","reviewCount":"7140"},"offers": {"@type": "Offer","url": "https://www.apprinting.com/blue-flowers-and-leaves-wedding-invitation/","priceCurrency": "USD","price": "85.00","priceValidUntil": "2024-12-24","itemCondition": "https://schema.org/UsedCondition","availability": "https://schema.org/InStock"}}`,
    `<meta name="keywords" content ="Spanish & English Wedding Invitation, Hispanic Wedding Invitations, Dual Language Invitations, Bilingual Wedding Cards, Cultural Wedding Stationery" />`,
  ],
  [
    `Top Bilingual Wedding Invitation Services for Your Special Day | AP PRINTING`,
    `Get the best bilingual wedding invitation services tailored to your needs. Our custom and personalized invitations will make your wedding unforgettable. Contact us today to start designing!`,
    `{"@context":"https://schema.org/","@type":"Product","name":"Burgundy and White Peony Spanish & English Wedding Invitation","description":"Burgundy and White Peony Spanish & English Wedding Invitation. A high-quality product offered by AP PRINTING. Our design team ensures that every detail is perfect to meet our customers' needs.","sku":"","brand":{"@type":"Card","name":"Bilingual Wedding Invitation"},"review":{"@type":"Review","reviewRating":{"@type":"Rating","ratingValue":"4","bestRating":"5"},"author":{"@type":"Person","name":"AP PRINTING DESIGN TEAM"}},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.6","reviewCount":"7546"},"offers": {"@type": "Offer","url": "https://www.apprinting.com/blue-flowers-and-leaves-wedding-invitation/","priceCurrency": "USD","price": "85.00","priceValidUntil": "2024-12-24","itemCondition": "https://schema.org/UsedCondition","availability": "https://schema.org/InStock"}}`,
    `<meta name="keywords" content ="Bilingual Wedding Invitation Services, Custom Wedding Invitations, Dual Language Invitations, Personalized Wedding Stationery, Wedding Invitation Printing" />`,
  ],
];

export default seoData;